// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package me.yabble.common.proto;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DelayedJobOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // required int64 item_id = 2;
    /**
     * <code>required int64 item_id = 2;</code>
     */
    boolean hasItemId();
    /**
     * <code>required int64 item_id = 2;</code>
     */
    long getItemId();

    // required string qname = 3;
    /**
     * <code>required string qname = 3;</code>
     */
    boolean hasQname();
    /**
     * <code>required string qname = 3;</code>
     */
    java.lang.String getQname();
    /**
     * <code>required string qname = 3;</code>
     */
    com.google.protobuf.ByteString
        getQnameBytes();

    // required string datetime_to_submit = 4;
    /**
     * <code>required string datetime_to_submit = 4;</code>
     */
    boolean hasDatetimeToSubmit();
    /**
     * <code>required string datetime_to_submit = 4;</code>
     */
    java.lang.String getDatetimeToSubmit();
    /**
     * <code>required string datetime_to_submit = 4;</code>
     */
    com.google.protobuf.ByteString
        getDatetimeToSubmitBytes();
  }
  /**
   * Protobuf type {@code me.yabble.common.proto.DelayedJob}
   */
  public static final class DelayedJob extends
      com.google.protobuf.GeneratedMessage
      implements DelayedJobOrBuilder {
    // Use DelayedJob.newBuilder() to construct.
    private DelayedJob(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DelayedJob(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DelayedJob defaultInstance;
    public static DelayedJob getDefaultInstance() {
      return defaultInstance;
    }

    public DelayedJob getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DelayedJob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              itemId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              qname_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              datetimeToSubmit_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_DelayedJob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_DelayedJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.yabble.common.proto.CommonProtos.DelayedJob.class, me.yabble.common.proto.CommonProtos.DelayedJob.Builder.class);
    }

    public static com.google.protobuf.Parser<DelayedJob> PARSER =
        new com.google.protobuf.AbstractParser<DelayedJob>() {
      public DelayedJob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DelayedJob(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DelayedJob> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // required int64 item_id = 2;
    public static final int ITEM_ID_FIELD_NUMBER = 2;
    private long itemId_;
    /**
     * <code>required int64 item_id = 2;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 item_id = 2;</code>
     */
    public long getItemId() {
      return itemId_;
    }

    // required string qname = 3;
    public static final int QNAME_FIELD_NUMBER = 3;
    private java.lang.Object qname_;
    /**
     * <code>required string qname = 3;</code>
     */
    public boolean hasQname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string qname = 3;</code>
     */
    public java.lang.String getQname() {
      java.lang.Object ref = qname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          qname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string qname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQnameBytes() {
      java.lang.Object ref = qname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string datetime_to_submit = 4;
    public static final int DATETIME_TO_SUBMIT_FIELD_NUMBER = 4;
    private java.lang.Object datetimeToSubmit_;
    /**
     * <code>required string datetime_to_submit = 4;</code>
     */
    public boolean hasDatetimeToSubmit() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string datetime_to_submit = 4;</code>
     */
    public java.lang.String getDatetimeToSubmit() {
      java.lang.Object ref = datetimeToSubmit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          datetimeToSubmit_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string datetime_to_submit = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDatetimeToSubmitBytes() {
      java.lang.Object ref = datetimeToSubmit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datetimeToSubmit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      itemId_ = 0L;
      qname_ = "";
      datetimeToSubmit_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatetimeToSubmit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, itemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getQnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDatetimeToSubmitBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, itemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getQnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDatetimeToSubmitBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.DelayedJob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.yabble.common.proto.CommonProtos.DelayedJob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.yabble.common.proto.DelayedJob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.yabble.common.proto.CommonProtos.DelayedJobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_DelayedJob_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_DelayedJob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.yabble.common.proto.CommonProtos.DelayedJob.class, me.yabble.common.proto.CommonProtos.DelayedJob.Builder.class);
      }

      // Construct using me.yabble.common.proto.CommonProtos.DelayedJob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        qname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        datetimeToSubmit_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_DelayedJob_descriptor;
      }

      public me.yabble.common.proto.CommonProtos.DelayedJob getDefaultInstanceForType() {
        return me.yabble.common.proto.CommonProtos.DelayedJob.getDefaultInstance();
      }

      public me.yabble.common.proto.CommonProtos.DelayedJob build() {
        me.yabble.common.proto.CommonProtos.DelayedJob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.yabble.common.proto.CommonProtos.DelayedJob buildPartial() {
        me.yabble.common.proto.CommonProtos.DelayedJob result = new me.yabble.common.proto.CommonProtos.DelayedJob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.qname_ = qname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.datetimeToSubmit_ = datetimeToSubmit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.yabble.common.proto.CommonProtos.DelayedJob) {
          return mergeFrom((me.yabble.common.proto.CommonProtos.DelayedJob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.yabble.common.proto.CommonProtos.DelayedJob other) {
        if (other == me.yabble.common.proto.CommonProtos.DelayedJob.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasQname()) {
          bitField0_ |= 0x00000004;
          qname_ = other.qname_;
          onChanged();
        }
        if (other.hasDatetimeToSubmit()) {
          bitField0_ |= 0x00000008;
          datetimeToSubmit_ = other.datetimeToSubmit_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasItemId()) {
          
          return false;
        }
        if (!hasQname()) {
          
          return false;
        }
        if (!hasDatetimeToSubmit()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.yabble.common.proto.CommonProtos.DelayedJob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.yabble.common.proto.CommonProtos.DelayedJob) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required int64 item_id = 2;
      private long itemId_ ;
      /**
       * <code>required int64 item_id = 2;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 item_id = 2;</code>
       */
      public long getItemId() {
        return itemId_;
      }
      /**
       * <code>required int64 item_id = 2;</code>
       */
      public Builder setItemId(long value) {
        bitField0_ |= 0x00000002;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 item_id = 2;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = 0L;
        onChanged();
        return this;
      }

      // required string qname = 3;
      private java.lang.Object qname_ = "";
      /**
       * <code>required string qname = 3;</code>
       */
      public boolean hasQname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string qname = 3;</code>
       */
      public java.lang.String getQname() {
        java.lang.Object ref = qname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          qname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string qname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getQnameBytes() {
        java.lang.Object ref = qname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          qname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string qname = 3;</code>
       */
      public Builder setQname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        qname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string qname = 3;</code>
       */
      public Builder clearQname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        qname_ = getDefaultInstance().getQname();
        onChanged();
        return this;
      }
      /**
       * <code>required string qname = 3;</code>
       */
      public Builder setQnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        qname_ = value;
        onChanged();
        return this;
      }

      // required string datetime_to_submit = 4;
      private java.lang.Object datetimeToSubmit_ = "";
      /**
       * <code>required string datetime_to_submit = 4;</code>
       */
      public boolean hasDatetimeToSubmit() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string datetime_to_submit = 4;</code>
       */
      public java.lang.String getDatetimeToSubmit() {
        java.lang.Object ref = datetimeToSubmit_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          datetimeToSubmit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string datetime_to_submit = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDatetimeToSubmitBytes() {
        java.lang.Object ref = datetimeToSubmit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datetimeToSubmit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string datetime_to_submit = 4;</code>
       */
      public Builder setDatetimeToSubmit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        datetimeToSubmit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string datetime_to_submit = 4;</code>
       */
      public Builder clearDatetimeToSubmit() {
        bitField0_ = (bitField0_ & ~0x00000008);
        datetimeToSubmit_ = getDefaultInstance().getDatetimeToSubmit();
        onChanged();
        return this;
      }
      /**
       * <code>required string datetime_to_submit = 4;</code>
       */
      public Builder setDatetimeToSubmitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        datetimeToSubmit_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:me.yabble.common.proto.DelayedJob)
    }

    static {
      defaultInstance = new DelayedJob(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:me.yabble.common.proto.DelayedJob)
  }

  public interface EmailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string from = 1;
    /**
     * <code>required string from = 1;</code>
     */
    boolean hasFrom();
    /**
     * <code>required string from = 1;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>required string from = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    // optional string from_name = 2;
    /**
     * <code>optional string from_name = 2;</code>
     */
    boolean hasFromName();
    /**
     * <code>optional string from_name = 2;</code>
     */
    java.lang.String getFromName();
    /**
     * <code>optional string from_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFromNameBytes();

    // optional string reply_to = 3;
    /**
     * <code>optional string reply_to = 3;</code>
     */
    boolean hasReplyTo();
    /**
     * <code>optional string reply_to = 3;</code>
     */
    java.lang.String getReplyTo();
    /**
     * <code>optional string reply_to = 3;</code>
     */
    com.google.protobuf.ByteString
        getReplyToBytes();

    // repeated string to = 4;
    /**
     * <code>repeated string to = 4;</code>
     */
    java.util.List<java.lang.String>
    getToList();
    /**
     * <code>repeated string to = 4;</code>
     */
    int getToCount();
    /**
     * <code>repeated string to = 4;</code>
     */
    java.lang.String getTo(int index);
    /**
     * <code>repeated string to = 4;</code>
     */
    com.google.protobuf.ByteString
        getToBytes(int index);

    // repeated string cc = 5;
    /**
     * <code>repeated string cc = 5;</code>
     */
    java.util.List<java.lang.String>
    getCcList();
    /**
     * <code>repeated string cc = 5;</code>
     */
    int getCcCount();
    /**
     * <code>repeated string cc = 5;</code>
     */
    java.lang.String getCc(int index);
    /**
     * <code>repeated string cc = 5;</code>
     */
    com.google.protobuf.ByteString
        getCcBytes(int index);

    // repeated string bcc = 6;
    /**
     * <code>repeated string bcc = 6;</code>
     */
    java.util.List<java.lang.String>
    getBccList();
    /**
     * <code>repeated string bcc = 6;</code>
     */
    int getBccCount();
    /**
     * <code>repeated string bcc = 6;</code>
     */
    java.lang.String getBcc(int index);
    /**
     * <code>repeated string bcc = 6;</code>
     */
    com.google.protobuf.ByteString
        getBccBytes(int index);

    // optional string subject = 7;
    /**
     * <code>optional string subject = 7;</code>
     */
    boolean hasSubject();
    /**
     * <code>optional string subject = 7;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>optional string subject = 7;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    // optional string text_body = 8;
    /**
     * <code>optional string text_body = 8;</code>
     */
    boolean hasTextBody();
    /**
     * <code>optional string text_body = 8;</code>
     */
    java.lang.String getTextBody();
    /**
     * <code>optional string text_body = 8;</code>
     */
    com.google.protobuf.ByteString
        getTextBodyBytes();

    // optional string html_body = 9;
    /**
     * <code>optional string html_body = 9;</code>
     */
    boolean hasHtmlBody();
    /**
     * <code>optional string html_body = 9;</code>
     */
    java.lang.String getHtmlBody();
    /**
     * <code>optional string html_body = 9;</code>
     */
    com.google.protobuf.ByteString
        getHtmlBodyBytes();
  }
  /**
   * Protobuf type {@code me.yabble.common.proto.Email}
   */
  public static final class Email extends
      com.google.protobuf.GeneratedMessage
      implements EmailOrBuilder {
    // Use Email.newBuilder() to construct.
    private Email(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Email(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Email defaultInstance;
    public static Email getDefaultInstance() {
      return defaultInstance;
    }

    public Email getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Email(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              from_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fromName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              replyTo_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                to_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              to_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                cc_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              cc_.add(input.readBytes());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                bcc_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              bcc_.add(input.readBytes());
              break;
            }
            case 58: {
              bitField0_ |= 0x00000008;
              subject_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000010;
              textBody_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000020;
              htmlBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          to_ = new com.google.protobuf.UnmodifiableLazyStringList(to_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          cc_ = new com.google.protobuf.UnmodifiableLazyStringList(cc_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          bcc_ = new com.google.protobuf.UnmodifiableLazyStringList(bcc_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_Email_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_Email_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.yabble.common.proto.CommonProtos.Email.class, me.yabble.common.proto.CommonProtos.Email.Builder.class);
    }

    public static com.google.protobuf.Parser<Email> PARSER =
        new com.google.protobuf.AbstractParser<Email>() {
      public Email parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Email(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Email> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string from = 1;
    public static final int FROM_FIELD_NUMBER = 1;
    private java.lang.Object from_;
    /**
     * <code>required string from = 1;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string from = 1;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          from_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string from = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string from_name = 2;
    public static final int FROM_NAME_FIELD_NUMBER = 2;
    private java.lang.Object fromName_;
    /**
     * <code>optional string from_name = 2;</code>
     */
    public boolean hasFromName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string from_name = 2;</code>
     */
    public java.lang.String getFromName() {
      java.lang.Object ref = fromName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string from_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromNameBytes() {
      java.lang.Object ref = fromName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string reply_to = 3;
    public static final int REPLY_TO_FIELD_NUMBER = 3;
    private java.lang.Object replyTo_;
    /**
     * <code>optional string reply_to = 3;</code>
     */
    public boolean hasReplyTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string reply_to = 3;</code>
     */
    public java.lang.String getReplyTo() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          replyTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reply_to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReplyToBytes() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string to = 4;
    public static final int TO_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList to_;
    /**
     * <code>repeated string to = 4;</code>
     */
    public java.util.List<java.lang.String>
        getToList() {
      return to_;
    }
    /**
     * <code>repeated string to = 4;</code>
     */
    public int getToCount() {
      return to_.size();
    }
    /**
     * <code>repeated string to = 4;</code>
     */
    public java.lang.String getTo(int index) {
      return to_.get(index);
    }
    /**
     * <code>repeated string to = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes(int index) {
      return to_.getByteString(index);
    }

    // repeated string cc = 5;
    public static final int CC_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList cc_;
    /**
     * <code>repeated string cc = 5;</code>
     */
    public java.util.List<java.lang.String>
        getCcList() {
      return cc_;
    }
    /**
     * <code>repeated string cc = 5;</code>
     */
    public int getCcCount() {
      return cc_.size();
    }
    /**
     * <code>repeated string cc = 5;</code>
     */
    public java.lang.String getCc(int index) {
      return cc_.get(index);
    }
    /**
     * <code>repeated string cc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCcBytes(int index) {
      return cc_.getByteString(index);
    }

    // repeated string bcc = 6;
    public static final int BCC_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList bcc_;
    /**
     * <code>repeated string bcc = 6;</code>
     */
    public java.util.List<java.lang.String>
        getBccList() {
      return bcc_;
    }
    /**
     * <code>repeated string bcc = 6;</code>
     */
    public int getBccCount() {
      return bcc_.size();
    }
    /**
     * <code>repeated string bcc = 6;</code>
     */
    public java.lang.String getBcc(int index) {
      return bcc_.get(index);
    }
    /**
     * <code>repeated string bcc = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBccBytes(int index) {
      return bcc_.getByteString(index);
    }

    // optional string subject = 7;
    public static final int SUBJECT_FIELD_NUMBER = 7;
    private java.lang.Object subject_;
    /**
     * <code>optional string subject = 7;</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string subject = 7;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subject_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subject = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string text_body = 8;
    public static final int TEXT_BODY_FIELD_NUMBER = 8;
    private java.lang.Object textBody_;
    /**
     * <code>optional string text_body = 8;</code>
     */
    public boolean hasTextBody() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string text_body = 8;</code>
     */
    public java.lang.String getTextBody() {
      java.lang.Object ref = textBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text_body = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTextBodyBytes() {
      java.lang.Object ref = textBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string html_body = 9;
    public static final int HTML_BODY_FIELD_NUMBER = 9;
    private java.lang.Object htmlBody_;
    /**
     * <code>optional string html_body = 9;</code>
     */
    public boolean hasHtmlBody() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string html_body = 9;</code>
     */
    public java.lang.String getHtmlBody() {
      java.lang.Object ref = htmlBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          htmlBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string html_body = 9;</code>
     */
    public com.google.protobuf.ByteString
        getHtmlBodyBytes() {
      java.lang.Object ref = htmlBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        htmlBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      from_ = "";
      fromName_ = "";
      replyTo_ = "";
      to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      subject_ = "";
      textBody_ = "";
      htmlBody_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFromBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReplyToBytes());
      }
      for (int i = 0; i < to_.size(); i++) {
        output.writeBytes(4, to_.getByteString(i));
      }
      for (int i = 0; i < cc_.size(); i++) {
        output.writeBytes(5, cc_.getByteString(i));
      }
      for (int i = 0; i < bcc_.size(); i++) {
        output.writeBytes(6, bcc_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(7, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(8, getTextBodyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(9, getHtmlBodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFromBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReplyToBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < to_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(to_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getToList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cc_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(cc_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCcList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bcc_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(bcc_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBccList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTextBodyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getHtmlBodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.yabble.common.proto.CommonProtos.Email parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.Email parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.yabble.common.proto.CommonProtos.Email prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.yabble.common.proto.Email}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.yabble.common.proto.CommonProtos.EmailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_Email_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_Email_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.yabble.common.proto.CommonProtos.Email.class, me.yabble.common.proto.CommonProtos.Email.Builder.class);
      }

      // Construct using me.yabble.common.proto.CommonProtos.Email.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fromName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        replyTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        bcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        subject_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        textBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        htmlBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_Email_descriptor;
      }

      public me.yabble.common.proto.CommonProtos.Email getDefaultInstanceForType() {
        return me.yabble.common.proto.CommonProtos.Email.getDefaultInstance();
      }

      public me.yabble.common.proto.CommonProtos.Email build() {
        me.yabble.common.proto.CommonProtos.Email result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.yabble.common.proto.CommonProtos.Email buildPartial() {
        me.yabble.common.proto.CommonProtos.Email result = new me.yabble.common.proto.CommonProtos.Email(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromName_ = fromName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.replyTo_ = replyTo_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          to_ = new com.google.protobuf.UnmodifiableLazyStringList(
              to_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.to_ = to_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          cc_ = new com.google.protobuf.UnmodifiableLazyStringList(
              cc_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.cc_ = cc_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          bcc_ = new com.google.protobuf.UnmodifiableLazyStringList(
              bcc_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.bcc_ = bcc_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.subject_ = subject_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000010;
        }
        result.textBody_ = textBody_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000020;
        }
        result.htmlBody_ = htmlBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.yabble.common.proto.CommonProtos.Email) {
          return mergeFrom((me.yabble.common.proto.CommonProtos.Email)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.yabble.common.proto.CommonProtos.Email other) {
        if (other == me.yabble.common.proto.CommonProtos.Email.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          bitField0_ |= 0x00000001;
          from_ = other.from_;
          onChanged();
        }
        if (other.hasFromName()) {
          bitField0_ |= 0x00000002;
          fromName_ = other.fromName_;
          onChanged();
        }
        if (other.hasReplyTo()) {
          bitField0_ |= 0x00000004;
          replyTo_ = other.replyTo_;
          onChanged();
        }
        if (!other.to_.isEmpty()) {
          if (to_.isEmpty()) {
            to_ = other.to_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureToIsMutable();
            to_.addAll(other.to_);
          }
          onChanged();
        }
        if (!other.cc_.isEmpty()) {
          if (cc_.isEmpty()) {
            cc_ = other.cc_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCcIsMutable();
            cc_.addAll(other.cc_);
          }
          onChanged();
        }
        if (!other.bcc_.isEmpty()) {
          if (bcc_.isEmpty()) {
            bcc_ = other.bcc_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureBccIsMutable();
            bcc_.addAll(other.bcc_);
          }
          onChanged();
        }
        if (other.hasSubject()) {
          bitField0_ |= 0x00000040;
          subject_ = other.subject_;
          onChanged();
        }
        if (other.hasTextBody()) {
          bitField0_ |= 0x00000080;
          textBody_ = other.textBody_;
          onChanged();
        }
        if (other.hasHtmlBody()) {
          bitField0_ |= 0x00000100;
          htmlBody_ = other.htmlBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrom()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.yabble.common.proto.CommonProtos.Email parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.yabble.common.proto.CommonProtos.Email) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string from = 1;
      private java.lang.Object from_ = "";
      /**
       * <code>required string from = 1;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string from = 1;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string from = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string from = 1;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string from = 1;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string from = 1;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        from_ = value;
        onChanged();
        return this;
      }

      // optional string from_name = 2;
      private java.lang.Object fromName_ = "";
      /**
       * <code>optional string from_name = 2;</code>
       */
      public boolean hasFromName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string from_name = 2;</code>
       */
      public java.lang.String getFromName() {
        java.lang.Object ref = fromName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fromName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromNameBytes() {
        java.lang.Object ref = fromName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from_name = 2;</code>
       */
      public Builder setFromName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fromName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_name = 2;</code>
       */
      public Builder clearFromName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromName_ = getDefaultInstance().getFromName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_name = 2;</code>
       */
      public Builder setFromNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fromName_ = value;
        onChanged();
        return this;
      }

      // optional string reply_to = 3;
      private java.lang.Object replyTo_ = "";
      /**
       * <code>optional string reply_to = 3;</code>
       */
      public boolean hasReplyTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string reply_to = 3;</code>
       */
      public java.lang.String getReplyTo() {
        java.lang.Object ref = replyTo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          replyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reply_to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReplyToBytes() {
        java.lang.Object ref = replyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reply_to = 3;</code>
       */
      public Builder setReplyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        replyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reply_to = 3;</code>
       */
      public Builder clearReplyTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        replyTo_ = getDefaultInstance().getReplyTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reply_to = 3;</code>
       */
      public Builder setReplyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        replyTo_ = value;
        onChanged();
        return this;
      }

      // repeated string to = 4;
      private com.google.protobuf.LazyStringList to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureToIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          to_ = new com.google.protobuf.LazyStringArrayList(to_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public java.util.List<java.lang.String>
          getToList() {
        return java.util.Collections.unmodifiableList(to_);
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public int getToCount() {
        return to_.size();
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public java.lang.String getTo(int index) {
        return to_.get(index);
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes(int index) {
        return to_.getByteString(index);
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public Builder setTo(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToIsMutable();
        to_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public Builder addTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToIsMutable();
        to_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public Builder addAllTo(
          java.lang.Iterable<java.lang.String> values) {
        ensureToIsMutable();
        super.addAll(values, to_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public Builder clearTo() {
        to_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string to = 4;</code>
       */
      public Builder addToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToIsMutable();
        to_.add(value);
        onChanged();
        return this;
      }

      // repeated string cc = 5;
      private com.google.protobuf.LazyStringList cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCcIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          cc_ = new com.google.protobuf.LazyStringArrayList(cc_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public java.util.List<java.lang.String>
          getCcList() {
        return java.util.Collections.unmodifiableList(cc_);
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public int getCcCount() {
        return cc_.size();
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public java.lang.String getCc(int index) {
        return cc_.get(index);
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCcBytes(int index) {
        return cc_.getByteString(index);
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public Builder setCc(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCcIsMutable();
        cc_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public Builder addCc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCcIsMutable();
        cc_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public Builder addAllCc(
          java.lang.Iterable<java.lang.String> values) {
        ensureCcIsMutable();
        super.addAll(values, cc_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public Builder clearCc() {
        cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cc = 5;</code>
       */
      public Builder addCcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCcIsMutable();
        cc_.add(value);
        onChanged();
        return this;
      }

      // repeated string bcc = 6;
      private com.google.protobuf.LazyStringList bcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBccIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          bcc_ = new com.google.protobuf.LazyStringArrayList(bcc_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public java.util.List<java.lang.String>
          getBccList() {
        return java.util.Collections.unmodifiableList(bcc_);
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public int getBccCount() {
        return bcc_.size();
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public java.lang.String getBcc(int index) {
        return bcc_.get(index);
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBccBytes(int index) {
        return bcc_.getByteString(index);
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public Builder setBcc(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBccIsMutable();
        bcc_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public Builder addBcc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBccIsMutable();
        bcc_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public Builder addAllBcc(
          java.lang.Iterable<java.lang.String> values) {
        ensureBccIsMutable();
        super.addAll(values, bcc_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public Builder clearBcc() {
        bcc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bcc = 6;</code>
       */
      public Builder addBccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBccIsMutable();
        bcc_.add(value);
        onChanged();
        return this;
      }

      // optional string subject = 7;
      private java.lang.Object subject_ = "";
      /**
       * <code>optional string subject = 7;</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string subject = 7;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subject = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subject = 7;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 7;</code>
       */
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000040);
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 7;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        subject_ = value;
        onChanged();
        return this;
      }

      // optional string text_body = 8;
      private java.lang.Object textBody_ = "";
      /**
       * <code>optional string text_body = 8;</code>
       */
      public boolean hasTextBody() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string text_body = 8;</code>
       */
      public java.lang.String getTextBody() {
        java.lang.Object ref = textBody_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          textBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text_body = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTextBodyBytes() {
        java.lang.Object ref = textBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text_body = 8;</code>
       */
      public Builder setTextBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        textBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text_body = 8;</code>
       */
      public Builder clearTextBody() {
        bitField0_ = (bitField0_ & ~0x00000080);
        textBody_ = getDefaultInstance().getTextBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text_body = 8;</code>
       */
      public Builder setTextBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        textBody_ = value;
        onChanged();
        return this;
      }

      // optional string html_body = 9;
      private java.lang.Object htmlBody_ = "";
      /**
       * <code>optional string html_body = 9;</code>
       */
      public boolean hasHtmlBody() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string html_body = 9;</code>
       */
      public java.lang.String getHtmlBody() {
        java.lang.Object ref = htmlBody_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          htmlBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string html_body = 9;</code>
       */
      public com.google.protobuf.ByteString
          getHtmlBodyBytes() {
        java.lang.Object ref = htmlBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          htmlBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string html_body = 9;</code>
       */
      public Builder setHtmlBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        htmlBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string html_body = 9;</code>
       */
      public Builder clearHtmlBody() {
        bitField0_ = (bitField0_ & ~0x00000100);
        htmlBody_ = getDefaultInstance().getHtmlBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string html_body = 9;</code>
       */
      public Builder setHtmlBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        htmlBody_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:me.yabble.common.proto.Email)
    }

    static {
      defaultInstance = new Email(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:me.yabble.common.proto.Email)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_me_yabble_common_proto_DelayedJob_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_me_yabble_common_proto_DelayedJob_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_me_yabble_common_proto_Email_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_me_yabble_common_proto_Email_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\026me.yabble.common.proto\"T" +
      "\n\nDelayedJob\022\n\n\002id\030\001 \002(\003\022\017\n\007item_id\030\002 \002(" +
      "\003\022\r\n\005qname\030\003 \002(\t\022\032\n\022datetime_to_submit\030\004" +
      " \002(\t\"\226\001\n\005Email\022\014\n\004from\030\001 \002(\t\022\021\n\tfrom_nam" +
      "e\030\002 \001(\t\022\020\n\010reply_to\030\003 \001(\t\022\n\n\002to\030\004 \003(\t\022\n\n" +
      "\002cc\030\005 \003(\t\022\013\n\003bcc\030\006 \003(\t\022\017\n\007subject\030\007 \001(\t\022" +
      "\021\n\ttext_body\030\010 \001(\t\022\021\n\thtml_body\030\t \001(\tB&\n" +
      "\026me.yabble.common.protoB\014CommonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_me_yabble_common_proto_DelayedJob_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_me_yabble_common_proto_DelayedJob_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_me_yabble_common_proto_DelayedJob_descriptor,
              new java.lang.String[] { "Id", "ItemId", "Qname", "DatetimeToSubmit", });
          internal_static_me_yabble_common_proto_Email_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_me_yabble_common_proto_Email_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_me_yabble_common_proto_Email_descriptor,
              new java.lang.String[] { "From", "FromName", "ReplyTo", "To", "Cc", "Bcc", "Subject", "TextBody", "HtmlBody", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
