// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package me.yabble.common.proto;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WorkQueueItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // optional bytes data = 2;
    /**
     * <code>optional bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    // optional string creation_date = 3;
    /**
     * <code>optional string creation_date = 3;</code>
     */
    boolean hasCreationDate();
    /**
     * <code>optional string creation_date = 3;</code>
     */
    java.lang.String getCreationDate();
    /**
     * <code>optional string creation_date = 3;</code>
     */
    com.google.protobuf.ByteString
        getCreationDateBytes();

    // optional string last_in_progress_date = 4;
    /**
     * <code>optional string last_in_progress_date = 4;</code>
     */
    boolean hasLastInProgressDate();
    /**
     * <code>optional string last_in_progress_date = 4;</code>
     */
    java.lang.String getLastInProgressDate();
    /**
     * <code>optional string last_in_progress_date = 4;</code>
     */
    com.google.protobuf.ByteString
        getLastInProgressDateBytes();

    // optional int64 attempt_count = 5;
    /**
     * <code>optional int64 attempt_count = 5;</code>
     */
    boolean hasAttemptCount();
    /**
     * <code>optional int64 attempt_count = 5;</code>
     */
    long getAttemptCount();

    // optional string timeout_date = 6;
    /**
     * <code>optional string timeout_date = 6;</code>
     */
    boolean hasTimeoutDate();
    /**
     * <code>optional string timeout_date = 6;</code>
     */
    java.lang.String getTimeoutDate();
    /**
     * <code>optional string timeout_date = 6;</code>
     */
    com.google.protobuf.ByteString
        getTimeoutDateBytes();

    // repeated string failure_message = 7;
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    java.util.List<java.lang.String>
    getFailureMessageList();
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    int getFailureMessageCount();
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    java.lang.String getFailureMessage(int index);
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    com.google.protobuf.ByteString
        getFailureMessageBytes(int index);
  }
  /**
   * Protobuf type {@code me.yabble.common.proto.WorkQueueItem}
   */
  public static final class WorkQueueItem extends
      com.google.protobuf.GeneratedMessage
      implements WorkQueueItemOrBuilder {
    // Use WorkQueueItem.newBuilder() to construct.
    private WorkQueueItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorkQueueItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorkQueueItem defaultInstance;
    public static WorkQueueItem getDefaultInstance() {
      return defaultInstance;
    }

    public WorkQueueItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorkQueueItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              creationDate_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              lastInProgressDate_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              attemptCount_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              timeoutDate_ = input.readBytes();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                failureMessage_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              failureMessage_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          failureMessage_ = new com.google.protobuf.UnmodifiableLazyStringList(failureMessage_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_WorkQueueItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_WorkQueueItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.yabble.common.proto.CommonProtos.WorkQueueItem.class, me.yabble.common.proto.CommonProtos.WorkQueueItem.Builder.class);
    }

    public static com.google.protobuf.Parser<WorkQueueItem> PARSER =
        new com.google.protobuf.AbstractParser<WorkQueueItem>() {
      public WorkQueueItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkQueueItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorkQueueItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // optional string creation_date = 3;
    public static final int CREATION_DATE_FIELD_NUMBER = 3;
    private java.lang.Object creationDate_;
    /**
     * <code>optional string creation_date = 3;</code>
     */
    public boolean hasCreationDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string creation_date = 3;</code>
     */
    public java.lang.String getCreationDate() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          creationDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string creation_date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCreationDateBytes() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string last_in_progress_date = 4;
    public static final int LAST_IN_PROGRESS_DATE_FIELD_NUMBER = 4;
    private java.lang.Object lastInProgressDate_;
    /**
     * <code>optional string last_in_progress_date = 4;</code>
     */
    public boolean hasLastInProgressDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string last_in_progress_date = 4;</code>
     */
    public java.lang.String getLastInProgressDate() {
      java.lang.Object ref = lastInProgressDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastInProgressDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last_in_progress_date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLastInProgressDateBytes() {
      java.lang.Object ref = lastInProgressDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastInProgressDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 attempt_count = 5;
    public static final int ATTEMPT_COUNT_FIELD_NUMBER = 5;
    private long attemptCount_;
    /**
     * <code>optional int64 attempt_count = 5;</code>
     */
    public boolean hasAttemptCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 attempt_count = 5;</code>
     */
    public long getAttemptCount() {
      return attemptCount_;
    }

    // optional string timeout_date = 6;
    public static final int TIMEOUT_DATE_FIELD_NUMBER = 6;
    private java.lang.Object timeoutDate_;
    /**
     * <code>optional string timeout_date = 6;</code>
     */
    public boolean hasTimeoutDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string timeout_date = 6;</code>
     */
    public java.lang.String getTimeoutDate() {
      java.lang.Object ref = timeoutDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeoutDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timeout_date = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTimeoutDateBytes() {
      java.lang.Object ref = timeoutDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeoutDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string failure_message = 7;
    public static final int FAILURE_MESSAGE_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList failureMessage_;
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    public java.util.List<java.lang.String>
        getFailureMessageList() {
      return failureMessage_;
    }
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    public int getFailureMessageCount() {
      return failureMessage_.size();
    }
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    public java.lang.String getFailureMessage(int index) {
      return failureMessage_.get(index);
    }
    /**
     * <code>repeated string failure_message = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFailureMessageBytes(int index) {
      return failureMessage_.getByteString(index);
    }

    private void initFields() {
      id_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      creationDate_ = "";
      lastInProgressDate_ = "";
      attemptCount_ = 0L;
      timeoutDate_ = "";
      failureMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCreationDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLastInProgressDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, attemptCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTimeoutDateBytes());
      }
      for (int i = 0; i < failureMessage_.size(); i++) {
        output.writeBytes(7, failureMessage_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCreationDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLastInProgressDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, attemptCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTimeoutDateBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < failureMessage_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(failureMessage_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFailureMessageList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.yabble.common.proto.CommonProtos.WorkQueueItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.yabble.common.proto.CommonProtos.WorkQueueItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.yabble.common.proto.WorkQueueItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.yabble.common.proto.CommonProtos.WorkQueueItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_WorkQueueItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_WorkQueueItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.yabble.common.proto.CommonProtos.WorkQueueItem.class, me.yabble.common.proto.CommonProtos.WorkQueueItem.Builder.class);
      }

      // Construct using me.yabble.common.proto.CommonProtos.WorkQueueItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        creationDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        lastInProgressDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        attemptCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        timeoutDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        failureMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.yabble.common.proto.CommonProtos.internal_static_me_yabble_common_proto_WorkQueueItem_descriptor;
      }

      public me.yabble.common.proto.CommonProtos.WorkQueueItem getDefaultInstanceForType() {
        return me.yabble.common.proto.CommonProtos.WorkQueueItem.getDefaultInstance();
      }

      public me.yabble.common.proto.CommonProtos.WorkQueueItem build() {
        me.yabble.common.proto.CommonProtos.WorkQueueItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.yabble.common.proto.CommonProtos.WorkQueueItem buildPartial() {
        me.yabble.common.proto.CommonProtos.WorkQueueItem result = new me.yabble.common.proto.CommonProtos.WorkQueueItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.creationDate_ = creationDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastInProgressDate_ = lastInProgressDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.attemptCount_ = attemptCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timeoutDate_ = timeoutDate_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          failureMessage_ = new com.google.protobuf.UnmodifiableLazyStringList(
              failureMessage_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.failureMessage_ = failureMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.yabble.common.proto.CommonProtos.WorkQueueItem) {
          return mergeFrom((me.yabble.common.proto.CommonProtos.WorkQueueItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.yabble.common.proto.CommonProtos.WorkQueueItem other) {
        if (other == me.yabble.common.proto.CommonProtos.WorkQueueItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasCreationDate()) {
          bitField0_ |= 0x00000004;
          creationDate_ = other.creationDate_;
          onChanged();
        }
        if (other.hasLastInProgressDate()) {
          bitField0_ |= 0x00000008;
          lastInProgressDate_ = other.lastInProgressDate_;
          onChanged();
        }
        if (other.hasAttemptCount()) {
          setAttemptCount(other.getAttemptCount());
        }
        if (other.hasTimeoutDate()) {
          bitField0_ |= 0x00000020;
          timeoutDate_ = other.timeoutDate_;
          onChanged();
        }
        if (!other.failureMessage_.isEmpty()) {
          if (failureMessage_.isEmpty()) {
            failureMessage_ = other.failureMessage_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureFailureMessageIsMutable();
            failureMessage_.addAll(other.failureMessage_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.yabble.common.proto.CommonProtos.WorkQueueItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.yabble.common.proto.CommonProtos.WorkQueueItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // optional string creation_date = 3;
      private java.lang.Object creationDate_ = "";
      /**
       * <code>optional string creation_date = 3;</code>
       */
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string creation_date = 3;</code>
       */
      public java.lang.String getCreationDate() {
        java.lang.Object ref = creationDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          creationDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string creation_date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCreationDateBytes() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string creation_date = 3;</code>
       */
      public Builder setCreationDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string creation_date = 3;</code>
       */
      public Builder clearCreationDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        creationDate_ = getDefaultInstance().getCreationDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string creation_date = 3;</code>
       */
      public Builder setCreationDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creationDate_ = value;
        onChanged();
        return this;
      }

      // optional string last_in_progress_date = 4;
      private java.lang.Object lastInProgressDate_ = "";
      /**
       * <code>optional string last_in_progress_date = 4;</code>
       */
      public boolean hasLastInProgressDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string last_in_progress_date = 4;</code>
       */
      public java.lang.String getLastInProgressDate() {
        java.lang.Object ref = lastInProgressDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastInProgressDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_in_progress_date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLastInProgressDateBytes() {
        java.lang.Object ref = lastInProgressDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastInProgressDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_in_progress_date = 4;</code>
       */
      public Builder setLastInProgressDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        lastInProgressDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_in_progress_date = 4;</code>
       */
      public Builder clearLastInProgressDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastInProgressDate_ = getDefaultInstance().getLastInProgressDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_in_progress_date = 4;</code>
       */
      public Builder setLastInProgressDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        lastInProgressDate_ = value;
        onChanged();
        return this;
      }

      // optional int64 attempt_count = 5;
      private long attemptCount_ ;
      /**
       * <code>optional int64 attempt_count = 5;</code>
       */
      public boolean hasAttemptCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 attempt_count = 5;</code>
       */
      public long getAttemptCount() {
        return attemptCount_;
      }
      /**
       * <code>optional int64 attempt_count = 5;</code>
       */
      public Builder setAttemptCount(long value) {
        bitField0_ |= 0x00000010;
        attemptCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 attempt_count = 5;</code>
       */
      public Builder clearAttemptCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        attemptCount_ = 0L;
        onChanged();
        return this;
      }

      // optional string timeout_date = 6;
      private java.lang.Object timeoutDate_ = "";
      /**
       * <code>optional string timeout_date = 6;</code>
       */
      public boolean hasTimeoutDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string timeout_date = 6;</code>
       */
      public java.lang.String getTimeoutDate() {
        java.lang.Object ref = timeoutDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timeoutDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timeout_date = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTimeoutDateBytes() {
        java.lang.Object ref = timeoutDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeoutDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timeout_date = 6;</code>
       */
      public Builder setTimeoutDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timeoutDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeout_date = 6;</code>
       */
      public Builder clearTimeoutDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timeoutDate_ = getDefaultInstance().getTimeoutDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeout_date = 6;</code>
       */
      public Builder setTimeoutDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timeoutDate_ = value;
        onChanged();
        return this;
      }

      // repeated string failure_message = 7;
      private com.google.protobuf.LazyStringList failureMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFailureMessageIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          failureMessage_ = new com.google.protobuf.LazyStringArrayList(failureMessage_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public java.util.List<java.lang.String>
          getFailureMessageList() {
        return java.util.Collections.unmodifiableList(failureMessage_);
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public int getFailureMessageCount() {
        return failureMessage_.size();
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public java.lang.String getFailureMessage(int index) {
        return failureMessage_.get(index);
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFailureMessageBytes(int index) {
        return failureMessage_.getByteString(index);
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public Builder setFailureMessage(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFailureMessageIsMutable();
        failureMessage_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public Builder addFailureMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFailureMessageIsMutable();
        failureMessage_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public Builder addAllFailureMessage(
          java.lang.Iterable<java.lang.String> values) {
        ensureFailureMessageIsMutable();
        super.addAll(values, failureMessage_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public Builder clearFailureMessage() {
        failureMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string failure_message = 7;</code>
       */
      public Builder addFailureMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFailureMessageIsMutable();
        failureMessage_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:me.yabble.common.proto.WorkQueueItem)
    }

    static {
      defaultInstance = new WorkQueueItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:me.yabble.common.proto.WorkQueueItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_me_yabble_common_proto_WorkQueueItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_me_yabble_common_proto_WorkQueueItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\026me.yabble.common.proto\"\245" +
      "\001\n\rWorkQueueItem\022\n\n\002id\030\001 \002(\003\022\014\n\004data\030\002 \001" +
      "(\014\022\025\n\rcreation_date\030\003 \001(\t\022\035\n\025last_in_pro" +
      "gress_date\030\004 \001(\t\022\025\n\rattempt_count\030\005 \001(\003\022" +
      "\024\n\014timeout_date\030\006 \001(\t\022\027\n\017failure_message" +
      "\030\007 \003(\tB&\n\026me.yabble.common.protoB\014Common" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_me_yabble_common_proto_WorkQueueItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_me_yabble_common_proto_WorkQueueItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_me_yabble_common_proto_WorkQueueItem_descriptor,
              new java.lang.String[] { "Id", "Data", "CreationDate", "LastInProgressDate", "AttemptCount", "TimeoutDate", "FailureMessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
