#!/bin/bash
set -e
source $(dirname $0)/include

if test -z "$APP_HOME"; then
  fatal "APP_HOME must be set"
fi

if test ! -d $APP_HOME; then
  info "APP_HOME directory will be created"
fi

mkdir -p $APP_HOME/{pid,etc,var/{log,run}}

if test ! -e $APP_HOME/search-mapping; then
  ln -s $BASEDIR/search/mapping $APP_HOME/search-mapping
fi

touch $APP_HOME/etc/override.properties
