#!/bin/bash
set -e
source $(dirname $0)/include

node build-lib/r.js -o \
  baseUrl=$BASEDIR/web/src/main/resource/web/static/js/ \
  paths.requireLib=vendor/require-2.1.10 \
  paths.text=vendor/require-text \
  paths.mustache=vendor/mustache \
  paths.moment=vendor/moment-2.0.0 \
  paths.template=$BASEDIR/web/src/main/resource/web/template/ \
  name=main \
  include=requireLib \
  out=$BASEDIR/web/src/main/resource/web/static/js/main.min.js