#!/bin/bash
set -e
source $(dirname $0)/include

function print-usage() {
  if test -n "$1"; then echo $1 1>&2; fi
  echo 1>&2

  echo "Usage: $(basename $0) [options] git-commit deploy-dir config" 1>&2
  echo "    -h    Print this help message" 1>&2
  echo 1>&2

  log "Exiting"
  exit 1;
}

while getopts "h" option; do
  case $option in
    h ) print-usage;;
    * ) print-usage "Unknown option: $option";;
  esac
done

shift $(($OPTIND - 1))

if test $# -ne 2; then
  print-usage "Two and only two arguments are allowed"
fi

deploy_dir=$1
config=$2

cd $BASEDIR

vdir=$deploy_dir/.versions/$version

ant clean dist-archive

mkdir -p $deploy_dir/{etc,pid}
cp -r $BASEDIR/config/$config/etc/* $deploy_dir/etc
mkdir -p $deploy_dir/var/log
mkdir -p $vdir
tar -C$vdir -xzf$BASEDIR/target/yabble-$version.tar.gz
ln -sf $vdir/{artifact,bin,db-schema,.env,lib,.source-version-hash,.version,.version-hash} $deploy_dir
chmod 755 $vdir/bin/*
chmod 644 $vdir/bin/{include,include-java,functions}

cd -
