#!/bin/bash
set -e
source $(dirname $0)/include

function print-usage() {
  if test -n "$1"; then echo $1 1>&2; fi
  echo 1>&2

  echo "Usage: $(basename $0) [options] version deploy-dir config" 1>&2
  echo "    -h    Print this help message" 1>&2
  echo 1>&2

  log "Exiting"
  exit 1;
}

while getopts "h" option; do
  case $option in
    h ) print-usage;;
    * ) print-usage "Unknown option: $option";;
  esac
done

shift $(($OPTIND - 1))

if test $# -ne 3; then
  print-usage "Three and only three arguments are allowed"
fi

version=$1
deploy_dir=$2
config=$3

vdir=$deploy_dir/.versions/$version

cd $BASEDIR

git reset --hard v$version

ant clean dist-archive

mkdir -p $deploy_dir/etc
cp -r $BASEDIR/config/$config/etc/* $deploy_dir/etc
mkdir -p $deploy_dir/var/log
mkdir -p $vdir
tar -C$vdir -xzf$BASEDIR/target/yabble-$version.tar.gz
ln -sf $vdir/{artifact,bin,db-schema,.env,lib,.source-version-hash,.version,.version-hash} $deploy_dir

cd -
